# Generated by Django 4.0.6 on 2022-08-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_text', models.CharField(max_length=50, verbose_name='用户名称')),
                ('api_key', models.CharField(max_length=50)),
                ('secret_key', models.CharField(max_length=50)),
                ('passphrase', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0, verbose_name='保证金')),
                ('flag', models.CharField(choices=[('0', '实盘'), ('1', '模拟')], default='0', max_length=10)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(default=0, editable=False)),
                ('operate', models.IntegerField(default=1, editable=False)),
                ('msg', models.TextField(blank=True, editable=False, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '交易账户信息',
                'verbose_name_plural': '交易账户信息',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='策略名称')),
                ('operate', models.IntegerField(default=0, editable=False)),
                ('status', models.IntegerField(default=0, editable=False)),
                ('msg', models.TextField(blank=True, editable=False, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
                ('account', models.CharField(max_length=50, verbose_name='登陆账户')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('strategy', models.CharField(default='MaTrade', editable=False, max_length=50)),
                ('trading', models.BooleanField(default=False, editable=False)),
                ('trader_text', models.CharField(editable=False, max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '交易员',
                'verbose_name_plural': '交易员',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordid', models.CharField(max_length=50)),
                ('instid', models.CharField(max_length=50)),
                ('posside', models.CharField(max_length=10, null=True)),
                ('side', models.CharField(max_length=10, null=True)),
                ('avgpx', models.CharField(max_length=20, null=True)),
                ('tptriggerpx', models.CharField(max_length=20, null=True)),
                ('tpordpx', models.CharField(max_length=20, null=True)),
                ('sltriggerpx', models.CharField(max_length=20, null=True)),
                ('slordpx', models.CharField(max_length=20, null=True)),
                ('algo_order_id', models.CharField(max_length=50, null=True)),
                ('tdmode', models.CharField(default='cross', max_length=20, null=True)),
                ('ccy', models.CharField(default='USDT', max_length=20, null=True)),
                ('ordtype', models.CharField(default='market', max_length=20, null=True)),
                ('sz', models.CharField(default='0', max_length=20, null=True)),
                ('px', models.CharField(max_length=20, null=True)),
                ('pnl', models.CharField(max_length=20, null=True)),
                ('lever', models.CharField(max_length=10, null=True)),
                ('fee', models.CharField(max_length=10, null=True)),
                ('close_position', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('msg', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('accountinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.accountinfo')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.question')),
            ],
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.trader'),
        ),
    ]
